# Generated by Django 4.2.1 on 2023-10-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Profile',
            fields=[
                ('updated_by', models.CharField(auto_created=True, default='admin', editable=False, max_length=50, null=True)),
                ('created_by', models.CharField(auto_created=True, default='admin', editable=False, max_length=50, null=True)),
                ('profile_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('profile_name', models.CharField(max_length=45)),
                ('in_file_path', models.TextField()),
                ('out_file_path', models.TextField()),
                ('archieve_path', models.TextField(verbose_name='archive path')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='audit_log',
            fields=[
                ('cpv_audit_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('in_file_name', models.CharField(max_length=250)),
                ('out_file_name', models.CharField(max_length=250)),
                ('converted_datetime', models.CharField(max_length=60)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=25, null=True)),
                ('cpv_System_Name', models.CharField(default='CPV', max_length=45, verbose_name='System Name')),
                ('profile_name', models.CharField(default='Pharma', max_length=45)),
            ],
            options={
                'verbose_name': 'audit Log',
                'verbose_name_plural': 'audit Logs',
            },
        ),
    ]
