# Generated by Django 4.2.1 on 2023-06-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertpvs', '0004_alter_add_profile_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='add_profile',
            name='archieve_path',
            field=models.TextField(verbose_name='archive path'),
        ),
        migrations.AlterField(
            model_name='audit_log',
            name='cpv_System_Name',
            field=models.CharField(default='CPV', max_length=45, verbose_name='System Name'),
        ),
    ]
