# Generated by Django 4.2.1 on 2023-06-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertpvs', '0005_alter_add_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_profile',
            name='profile_name',
            field=models.CharField(max_length=45),
        ),
    ]
