# Generated by Django 4.2.1 on 2023-06-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertpvs', '0006_alter_add_profile_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_Profile',
            fields=[
                ('updated_by', models.CharField(auto_created=True, default='admin', editable=False, max_length=50, null=True)),
                ('created_by', models.CharField(auto_created=True, default='admin', editable=False, max_length=50, null=True)),
                ('profile_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('profile_name', models.CharField(max_length=45)),
                ('in_file_path', models.TextField()),
                ('out_file_path', models.TextField()),
                ('archive_path', models.TextField(verbose_name='archive path')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
