# Generated by Django 4.2.1 on 2023-06-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convertpvs', '0007_config_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config_Profile',
        ),
    ]
