# Generated by Django 4.2.1 on 2023-06-25 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convertpvs', '0009_customperiodictask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPeriodicTask',
        ),
    ]
